version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network  # Ensure frontend is on the same network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app_network  # Ensure backend is on the same network

networks:
  app_network:
    driver: bridge  # Use the bridge network driver to allow communication between containers
